version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.0

    steps:
      - checkout

      - restore_cache:
          keys: ['dcme-site-deps-{{ checksum "yarn.lock" }}']

      - run: yarn prep

      - save_cache:
          key: dcme-site-deps-{{ checksum "yarn.lock" }}
          paths: ['packages/dcme-style/node_modules']

      - run: git diff | cat
      - run: test -z "$(git status --porcelain)"
      - run: yarn test-all
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.0

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Set git creds
          command: |
            git config --global user.email "dxinteractive@gmail.com"
            git config --global user.name "dxinteractive"
      - add_ssh_keys:
          fingerprints:
              - "21:e7:14:cf:54:79:45:21:bb:bb:4d:08:42:6d:6c:ae"
      - run:
          name: "Deploy to gh-pages"
          command: yarn deploy
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
